version: '3.7'

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.13-alpine
  working_dir: /oleic
  restart: always
  volumes:
    - .:/oleic:cached
    - ./node_modules:/oleic/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  server:
    <<: *node
    working_dir: /oleic/server
    entrypoint: ["../node_modules/.bin/gulp"]
    environment:
      <<: *env
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 43190
    ports:
      - "43190:80"
    hostname: server

volumes:
  yarn-cache: {}
